In [2]:
import praw
import pandas as pd
import datetime
from matplotlib import pyplot as plt
import numpy as np

/Users/xiaoxiangma/.local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

In [3]:
import twint
import pickle
import nltk
import nest_asyncio
nest_asyncio.apply()

In [4]:
import datetime

In [5]:
def gen_time_window(start, end, step, length):
    
    start_datetime_object = datetime.datetime.strptime(start, '%Y-%m-%d')
    
    end_datetime_object = datetime.datetime.strptime(end, '%Y-%m-%d')

    iterator = start_datetime_object
    output = []
    while iterator < end_datetime_object:
        since = str(iterator)[:10]
#         until = str(iterator + datetime.timedelta(days=step))[:10]
        until = str(min(end_datetime_object, iterator + datetime.timedelta(days=length)))[:10]
        output.append((since,until))
        iterator += datetime.timedelta(days=step)
    
    return output

In [6]:
gen_time_window('2018-01-01', '2020-06-04', 14, 1)

[('2018-01-01', '2018-01-02'),
 ('2018-01-15', '2018-01-16'),
 ('2018-01-29', '2018-01-30'),
 ('2018-02-12', '2018-02-13'),
 ('2018-02-26', '2018-02-27'),
 ('2018-03-12', '2018-03-13'),
 ('2018-03-26', '2018-03-27'),
 ('2018-04-09', '2018-04-10'),
 ('2018-04-23', '2018-04-24'),
 ('2018-05-07', '2018-05-08'),
 ('2018-05-21', '2018-05-22'),
 ('2018-06-04', '2018-06-05'),
 ('2018-06-18', '2018-06-19'),
 ('2018-07-02', '2018-07-03'),
 ('2018-07-16', '2018-07-17'),
 ('2018-07-30', '2018-07-31'),
 ('2018-08-13', '2018-08-14'),
 ('2018-08-27', '2018-08-28'),
 ('2018-09-10', '2018-09-11'),
 ('2018-09-24', '2018-09-25'),
 ('2018-10-08', '2018-10-09'),
 ('2018-10-22', '2018-10-23'),
 ('2018-11-05', '2018-11-06'),
 ('2018-11-19', '2018-11-20'),
 ('2018-12-03', '2018-12-04'),
 ('2018-12-17', '2018-12-18'),
 ('2018-12-31', '2019-01-01'),
 ('2019-01-14', '2019-01-15'),
 ('2019-01-28', '2019-01-29'),
 ('2019-02-11', '2019-02-12'),
 ('2019-02-25', '2019-02-26'),
 ('2019-03-11', '2019-03-12'),
 ('2019-03-25', '2019-03-26'),
 ('2019-04-08', '2019-04-09'),
 ('2019-04-22', '2019-04-23'),
 ('2019-05-06', '2019-05-07'),
 ('2019-05-20', '2019-05-21'),
 ('2019-06-03', '2019-06-04'),
 ('2019-06-17', '2019-06-18'),
 ('2019-07-01', '2019-07-02'),
 ('2019-07-15', '2019-07-16'),
 ('2019-07-29', '2019-07-30'),
 ('2019-08-12', '2019-08-13'),
 ('2019-08-26', '2019-08-27'),
 ('2019-09-09', '2019-09-10'),
 ('2019-09-23', '2019-09-24'),
 ('2019-10-07', '2019-10-08'),
 ('2019-10-21', '2019-10-22'),
 ('2019-11-04', '2019-11-05'),
 ('2019-11-18', '2019-11-19'),
 ('2019-12-02', '2019-12-03'),
 ('2019-12-16', '2019-12-17'),
 ('2019-12-30', '2019-12-31'),
 ('2020-01-13', '2020-01-14'),
 ('2020-01-27', '2020-01-28'),
 ('2020-02-10', '2020-02-11'),
 ('2020-02-24', '2020-02-25'),
 ('2020-03-09', '2020-03-10'),
 ('2020-03-23', '2020-03-24'),
 ('2020-04-06', '2020-04-07'),
 ('2020-04-20', '2020-04-21'),
 ('2020-05-04', '2020-05-05'),
 ('2020-05-18', '2020-05-19'),
 ('2020-06-01', '2020-06-02')]

In [7]:
def get_tweets(search, since, until, limit=100, db=True):
    dbname = search.replace(" ","_") + ".db"
    c = twint.Config()
    c.Search = search
    c.Limit = limit # If not specified, scrapes all...
    c.Pandas = True
    c.Pandas_clean = True
    c.Since = since
    c.Until = until
    c.Database = dbname
    c.Hide_output = True
    
    twint.run.Search(c)
    if db==False:
        return twint.output.panda.Tweets_df
    else: print("Done: "+ since + " to " + until, twint.output.panda.Tweets_df.shape[0], "entries")

In [8]:
def scrape_to_db(keyword, start_date, end_date, step, length, limit):
    dates = gen_time_window(start_date, end_date, step, length)
    for i in dates:
        get_tweets(keyword, i[0], i[1], limit=limit)

In [40]:
scrape_to_db(keyword = "spacex rocket", 
             start_date = '2020-01-01', 
             end_date = '2020-06-01', 
             step = 30, 
             length = 1, 
             limit = 100)

[+] Inserting into Database: spacex_rocket.db
Done: 2020-01-01 to 2020-01-02 55 entries
[+] Inserting into Database: spacex_rocket.db
Done: 2020-01-31 to 2020-02-01 100 entries
[+] Inserting into Database: spacex_rocket.db
Done: 2020-03-01 to 2020-03-02 100 entries
[+] Inserting into Database: spacex_rocket.db
Done: 2020-03-31 to 2020-04-01 100 entries
[+] Inserting into Database: spacex_rocket.db
Done: 2020-04-30 to 2020-05-01 100 entries
[+] Inserting into Database: spacex_rocket.db
Done: 2020-05-30 to 2020-05-31 100 entries

In [ ]:
scrape_to_db(keyword = "digital health", 
             start_date = '2018-01-01', 
             end_date = '2020-06-01', 
             step = 14, 
             length = 1, 
             limit = 1000)

[+] Inserting into Database: digital_health.db
Done: 2018-01-01 to 2018-01-02 346 entries
[+] Inserting into Database: digital_health.db

In [37]:
tweets = get_tweets("digital health", '2020-06-03','2020-06-04', limit=100)
tweets = get_tweets("digital health", '2020-06-01','2020-06-02', limit=100)

# tweets.shape

[+] Inserting into Database: digital_health.db
Done: 2020-06-03 to 2020-06-04 100 entries
[+] Inserting into Database: digital_health.db
Done: 2020-06-01 to 2020-06-02 100 entries

In [ ]:
# pd.set_option("max_columns", None)

# pd.reset_option("max_rows")

In [17]:
tweets

,id,conversation_id,created_at,date,timezone,place,tweet,hashtags,cashtags,user_id,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1268331458122469376,1268331458122469376,1591228758000,2020-06-03 19:59:18,EDT,,Sharecare Acquires Evidence-Based Behavior Cha...,"[#digitaltherapeutics, #digitalhealth, #mhealt...",[],24249169,...,,,,,,"[{'user_id': '24249169', 'username': 'hitconsu...",,,,
1,1268330871037349888,1268330871037349888,1591228618000,2020-06-03 19:56:58,EDT,,Inspire Medical Systems Introduces Digital Hea...,[],[$insp],1134049078424162304,...,,,,,,"[{'user_id': '1134049078424162304', 'username'...",,,,
2,1268329865536663552,1268329865536663552,1591228379000,2020-06-03 19:52:59,EDT,,"As usual, if you couldn't tune in to today's l...","[#covid19, #youtube]",[],805004869,...,,,,,,"[{'user_id': '805004869', 'username': 'scripps...",,,,
3,1268328737218723847,1268328737218723847,1591228110000,2020-06-03 19:48:30,EDT,,BD to Present at Investor Conferences \n\nREAD...,"[#cure, #digitalhealth, #healthcare, #infograp...",[],226310002,...,,,,,,"[{'user_id': '226310002', 'username': 'IAM__Ne...",,,,
4,1268328305855352832,1268328305855352832,1591228007000,2020-06-03 19:46:47,EDT,,Program out now for #FromTheFrontlines on 26 J...,"[#fromthefrontlines, #nurse, #covid19, #earlyb...",[],128880885,...,,,,,,"[{'user_id': '128880885', 'username': 'TheInst...",,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,1268129326970568704,1268129326970568704,1591180566000,2020-06-03 06:36:06,EDT,,In der neuen Ausgabe des SWEET SPOT Magazins f...,"[#digitalhealth, #mentalhealth, #entrepreneurs...",[],4112626049,...,,,,,,"[{'user_id': '4112626049', 'username': 'Selfap...",,,,
636,1268129275967873024,1268129275967873024,1591180554000,2020-06-03 06:35:54,EDT,,Designing for Behavior Change #DigitalHealth #...,"[#digitalhealth, #digital, #health]",[],1224237141489680384,...,,,,,,"[{'user_id': '1224237141489680384', 'username'...",,,,
637,1268129179213664256,1268129179213664256,1591180531000,2020-06-03 06:35:31,EDT,,Mental health app downloads jump 24% in April ...,"[#pandemic, #digitalhealth]",[],25981856,...,,,,,,"[{'user_id': '25981856', 'username': 'julieodo...",,,,
638,1268128641411678208,1268128641411678208,1591180403000,2020-06-03 06:33:23,EDT,,Find out how to develop digital health solutio...,"[#digitalhealth, #pharma, #patientsolutions]",[],2791168761,...,,,,,,"[{'user_id': '2791168761', 'username': 'S3Conn...",,,,
639,1268128583735705600,1268128583735705600,1591180389000,2020-06-03 06:33:09,EDT,,"Celebrating 70 years of care | News, Sports, J...","[#cure, #digitalhealth, #healthcare, #infograp...",[],226310002,...,,,,,,"[{'user_id': '226310002', 'username': 'IAM__Ne...",,,,

In [ ]:
tweets['tweet']

In [ ]:
import json
with open('gender/top_words.json') as json_file:
    top_words = json.load(json_file)

In [ ]:
def find_features(top_words, text):
    feature = {}
    for word in top_words:
        feature[word] = word in text.lower()
    return feature

In [ ]:
NB_classifier = pickle.load(open('gender/gender_NB_classifier.sav', 'rb'))

In [ ]:
tweets['tweet'][0]

In [ ]:
NB_classifier.classify(find_features(top_words, tweets['tweet'][0]))

In [ ]:
tweets['gender'] = tweets['tweet'].apply(lambda x: NB_classifier.classify(find_features(top_words, x)))

In [ ]:
tweets['gender'].value_counts()

In [ ]:
!jupyter nbconvert --to script gender_classif.ipynb